Split backend and extension
trussed-dev/trussed-auth pull request #43
Opened 2024-04-02 19:51 UTC by robin-nitrokey

This patch splits the trussed-auth crate into two crates:  trussed-auth only defines the AuthExtension and can be used by clients or other backends implementing the extension.  trussed-auth-backend contains the AuthBackend that implements the extension using the filesystem.

2024-04-11 12:32 UTC, sosthene-nitrokey requested changes
I think we should be constistent with the other extensions/backends.

The implementation goes at the top level, the extension goes in to an `extension` top-level directory.

I fundamentally don't care much for it, but It should be consistent across crates.

2024-04-12 09:54 UTC, robin-nitrokey commented
I think the main difference to the other repositories is that in this case, the extension is the main component, not the backend.  So what should, for example, happen with the changelog?  It would be consistent to have the backend changelog in `.` and the extension changelog in `extension`, but I would find it confusing if the root changelog exists but does not contain the changes for the main crate of the repository.

2025-01-06 16:23 UTC, robin-nitrokey commented
@sosthene-nitrokey Do you still want to move the backend to the top level?

2025-01-21 12:50 UTC, daringer commented
this might be worth doing towards the next test releases, added it... I'd cast my vote against moving the backend to top-lvl, but it's max a 1/2 vote

2025-01-21 13:59 UTC, sosthene-nitrokey commented
Ok, then it's 2/1 so let's keep it the way it is.

2025-01-21 13:59 UTC, sosthene-nitrokey approved these changes

2025-01-21 20:17 UTC, merged